# Generated by Django 5.0.14 on 2026-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
