# Generated by Django 5.0.14 on 2026-08-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='students.studentprofile'),
        ),
    ]
