# Generated by Django 5.2.17 on 2026-09-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_learningmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='learningmaterial',
            new_name='content_lea_class_s_ca92f5_idx',
            old_name='content_le_class_s_idx',
        ),
        migrations.RenameIndex(
            model_name='learningmaterial',
            new_name='content_lea_chapter_e581d8_idx',
            old_name='content_le_chapter_idx',
        ),
    ]
